# Generated by Django 2.2.13 on 2020-06-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='updated_on',
        ),
    ]
