# Generated by Django 2.2.13 on 2020-06-07 22:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200607_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=128),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='account/staff/'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.StaffRole'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='uid',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='updated_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
