# Generated by Django 2.2.13 on 2020-06-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200619_1631'),
        ('account', '0002_auto_20200613_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mother_tounge',
            new_name='language',
        ),
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.Standard')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.Profile')),
            ],
        ),
    ]
