# Generated by Django 2.2.13 on 2020-06-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200608_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='uid',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
