# Generated by Django 2.2.13 on 2020-06-13 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('grn', models.IntegerField(primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=19)),
                ('uid', models.CharField(blank=True, max_length=12, null=True)),
                ('first_name', models.CharField(max_length=256)),
                ('middle_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8)),
                ('cast', models.CharField(max_length=256)),
                ('admission_date', models.DateField()),
                ('mother_first_name', models.CharField(blank=True, max_length=256, null=True)),
                ('father_middle_name', models.CharField(blank=True, max_length=256, null=True)),
                ('nationality', models.CharField(default='Indian', max_length=256)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student/%Y/%m/%d/')),
                ('last_school', models.CharField(blank=True, max_length=256, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.CastCategory')),
                ('mother_tongue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.Language')),
                ('religion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.Religion')),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='school.Standard')),
            ],
        ),
    ]
